### ISSUE TITLE
JSON.

### ISSUE THREAD

**Issue by AaruniJha** [PetroIvaniuk/2022-Ukraine-Russia-War-Dataset#1]
Your json links don't work. Making a request to a server return the response in text/HTML.

**Comment by PetroIvaniuk** [comment]
Can you share how you do the request?

**Comment by AaruniJha** [comment]
import json
import pandas 
import requests

response = requests.get('https://github.com/PetroIvaniuk/2022-Ukraine-Russia-War-Dataset/blob/main/data/russia_losses_equipment.json')

response.status_code

dict1  = response.json ## **JSONDecodeError: Expecting value: line 7 column 1 (char 6)**

**Comment by AaruniJha** [comment]
????

**Comment by PetroIvaniuk** [comment]
> import json import pandas import requests
> 
> response = requests.get('https://github.com/PetroIvaniuk/2022-Ukraine-Russia-War-Dataset/blob/main/data/russia_losses_equipment.json')
> 
> response.status_code
> 
> dict1 = response.json ## **JSONDecodeError: Expecting value: line 7 column 1 (char 6)**

try this one:
```
import json, requests
import pandas as pd

url = 'https://raw.githubusercontent.com/PetroIvaniuk/2022-Ukraine-Russia-War-Dataset/main/data/russia_losses_equipment.json'
response = requests.get(url)
df = pd.DataFrame(response.json())
df.head()
```

**Comment by AaruniJha** [comment]
Thank You for helping out. It works!!!!

**Comment by AaruniJha** [comment]
Could you also send the link for losses in personnel?

I tried the code below

url = 'https://github.com/PetroIvaniuk/2022-Ukraine-Russia-War-Dataset/blob/main/data/russia_losses_personnel.json'
response = requests.get(url)
df = pd.DataFrame(response.json())
df.head()

But it returns the same error.

Thank You!!

**Comment by PetroIvaniuk** [comment]
https://raw.githubusercontent.com/PetroIvaniuk/2022-Ukraine-Russia-War-Dataset/main/data/russia_losses_personnel.json
