### ISSUE TITLE
Can you please provide the json link that works properly? 

### ISSUE THREAD

**Issue by AaruniJha** [PetroIvaniuk/2022-Ukraine-Russia-War-Dataset#2]

**Comment by PetroIvaniuk** [comment]
It is a direct link to the data https://github.com/PetroIvaniuk/2022-Ukraine-Russia-War-Dataset/blob/main/data/russia_losses_equipment.json. What do you mean?

**Comment by PetroIvaniuk** [comment]
https://raw.githubusercontent.com/PetroIvaniuk/2022-Ukraine-Russia-War-Dataset/main/data/russia_losses_personnel.json
https://raw.githubusercontent.com/PetroIvaniuk/2022-Ukraine-Russia-War-Dataset/main/data/russia_losses_equipment.json
