### ISSUE TITLE
Proposal about daily loss

### ISSUE THREAD

**Issue by Bleach665** [PetroIvaniuk/2022-Ukraine-Russia-War-Dataset#3]
Could you please add a single file with daily rus loses? Reason is to get it in convenient way on different controllers where downloading and parsing is not trivial.

**Comment by PetroIvaniuk** [comment]
> Could you please add a single file with daily rus loses? Reason is to get it in convenient way on different controllers where downloading and parsing is not trivial.

You can easily join two files based on date or day key
